import type { LucideProps } from 'lucide-react'
import {
  Home,
  Calendar,
  FileText,
  FolderKanban,
  Wallet,
  Copy,
  UserCog,
  LayoutTemplate,
  Settings,
  Table,
  Sun,
  Moon,
  LogOut,
  Menu,
  X,
  ChevronDown,
  ChevronRight,
  ChevronLeft,
  Search,
  Plus,
  SlidersHorizontal,
  AlertTriangle,
  Link2,
  Check,
  Upload,
  Download,
  Printer,
  Send,
  Clock,
  ChevronUp,
  Trash2,
  Pencil,
  RefreshCw,
  ArrowRight,
  ArrowLeft,
  Phone,
  Mail,
  Landmark,
  Inbox,
  Sparkles,
  Loader2,
  Lock,
} from 'lucide-react'

// Rediseño Apple-style: los íconos y tonos del nav siguen exactamente
// data.js > SN5.nav del skill (home/gray, file-text/gray, folder-kanban/blue,
// wallet/green, user-cog/indigo, calendar/red, layout-template/teal,
// settings/gray) -- ver components/navigation/NavItem.tsx para el chip de
// color. 'google-sheets' no tiene equivalente en el kit (Admin es una sola
// entrada ahí); se deja Table por ser la más descriptiva.
const ICONS = {
  dashboard: Home,
  planeacion: Calendar,
  calendar: Calendar,
  cotizaciones: FileText,
  proyectos: FolderKanban,
  cuentas: Wallet,
  proveedores: UserCog,
  plantillas: LayoutTemplate,
  admin: Settings,
  'admin-usuarios': Settings,
  'google-sheets': Table,
  'theme-light': Sun,
  'theme-dark': Moon,
  copy: Copy,
  'log-out': LogOut,
  menu: Menu,
  close: X,
  'chevron-down': ChevronDown,
  'chevron-right': ChevronRight,
  'chevron-left': ChevronLeft,
  search: Search,
  plus: Plus,
  filter: SlidersHorizontal,
  warning: AlertTriangle,
  link: Link2,
  check: Check,
  'file-text': FileText,
  upload: Upload,
  download: Download,
  printer: Printer,
  send: Send,
  clock: Clock,
  'chevron-up': ChevronUp,
  trash: Trash2,
  edit: Pencil,
  refresh: RefreshCw,
  'arrow-right': ArrowRight,
  'arrow-left': ArrowLeft,
  phone: Phone,
  mail: Mail,
  landmark: Landmark,
  inbox: Inbox,
  sparkles: Sparkles,
  loader: Loader2,
  lock: Lock,
} as const

export type IconName = keyof typeof ICONS

interface IconProps extends Omit<LucideProps, 'ref'> {
  name: IconName
}

export function Icon({ name, size = 18, strokeWidth = 2, ...rest }: IconProps) {
  const LucideIcon = ICONS[name]
  return <LucideIcon size={size} strokeWidth={strokeWidth} aria-hidden="true" {...rest} />
}
