import type { LucideProps } from 'lucide-react'
import {
  Home,
  Calendar,
  FileText,
  FolderKanban,
  Wallet,
  Copy,
  UserCog,
  LayoutTemplate,
  Settings,
  Table,
  Sun,
  Moon,
  LogOut,
  Menu,
  X,
  ChevronDown,
  ChevronRight,
  ChevronLeft,
  Search,
  Plus,
  SlidersHorizontal,
  AlertTriangle,
  Link2,
  Check,
  Upload,
  Download,
  Printer,
  Send,
  Clock,
  ChevronUp,
  Trash2,
  Pencil,
  RefreshCw,
  ArrowRight,
  ArrowLeft,
  Phone,
  Mail,
  Landmark,
  Inbox,
  Sparkles,
  Loader2,
  Lock,
  Users,
  Bold,
  AlignLeft,
  AlignCenter,
  AlignRight,
  AlignJustify,
  CaseSensitive,
  Minus,
  Image as ImageIcon,
  DollarSign,
  BringToFront,
  SendToBack,
  Table2,
  Type,
  AlignHorizontalJustifyStart,
  AlignHorizontalJustifyCenter,
  AlignHorizontalJustifyEnd,
  AlignVerticalJustifyStart,
  AlignVerticalJustifyCenter,
  AlignVerticalJustifyEnd,
} from 'lucide-react'

// Rediseño Apple-style: los íconos y tonos del nav siguen exactamente
// data.js > SN5.nav del skill (home/gray, file-text/gray, folder-kanban/blue,
// wallet/green, user-cog/indigo, calendar/red, layout-template/teal,
// settings/gray) -- ver components/navigation/NavItem.tsx para el chip de
// color. 'google-sheets' no tiene equivalente en el kit (Admin es una sola
// entrada ahí); se deja Table por ser la más descriptiva.
const ICONS = {
  dashboard: Home,
  planeacion: Calendar,
  calendar: Calendar,
  cotizaciones: FileText,
  proyectos: FolderKanban,
  cuentas: Wallet,
  proveedores: UserCog,
  // Bloque 5 (docs/PLAN.md): sin equivalente en el kit -- Users es la más
  // descriptiva (mismo criterio que 'google-sheets'/Table más arriba).
  clientes: Users,
  plantillas: LayoutTemplate,
  'editor-pdfs': LayoutTemplate,
  admin: Settings,
  'admin-usuarios': Settings,
  'google-sheets': Table,
  'theme-light': Sun,
  'theme-dark': Moon,
  copy: Copy,
  'log-out': LogOut,
  menu: Menu,
  close: X,
  'chevron-down': ChevronDown,
  'chevron-right': ChevronRight,
  'chevron-left': ChevronLeft,
  search: Search,
  plus: Plus,
  filter: SlidersHorizontal,
  warning: AlertTriangle,
  link: Link2,
  check: Check,
  'file-text': FileText,
  upload: Upload,
  download: Download,
  printer: Printer,
  send: Send,
  clock: Clock,
  'chevron-up': ChevronUp,
  trash: Trash2,
  edit: Pencil,
  refresh: RefreshCw,
  'arrow-right': ArrowRight,
  'arrow-left': ArrowLeft,
  phone: Phone,
  mail: Mail,
  landmark: Landmark,
  inbox: Inbox,
  sparkles: Sparkles,
  loader: Loader2,
  lock: Lock,
  // Editor de PDFs (docs/PLAN.md, Bloque 7 -- rediseño del lienzo): toolbar
  // contextual, capas e íconos de tipo de elemento.
  bold: Bold,
  'align-left': AlignLeft,
  'align-center': AlignCenter,
  'align-right': AlignRight,
  'align-justify': AlignJustify,
  'case-sensitive': CaseSensitive,
  minus: Minus,
  image: ImageIcon,
  'dollar-sign': DollarSign,
  'bring-to-front': BringToFront,
  'send-to-back': SendToBack,
  'table-2': Table2,
  type: Type,
  'align-h-start': AlignHorizontalJustifyStart,
  'align-h-center': AlignHorizontalJustifyCenter,
  'align-h-end': AlignHorizontalJustifyEnd,
  'align-v-start': AlignVerticalJustifyStart,
  'align-v-center': AlignVerticalJustifyCenter,
  'align-v-end': AlignVerticalJustifyEnd,
} as const

export type IconName = keyof typeof ICONS

interface IconProps extends Omit<LucideProps, 'ref'> {
  name: IconName
}

export function Icon({ name, size = 18, strokeWidth = 2, ...rest }: IconProps) {
  const LucideIcon = ICONS[name]
  return <LucideIcon size={size} strokeWidth={strokeWidth} aria-hidden="true" {...rest} />
}
